name: CI

on:
  push:
    branches: ['**']
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint (Node 20.x)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Biome (core, static, sdk)
        run: |
          pnpm --filter @paraport/core exec biome ci .
          pnpm --filter @paraport/static exec biome ci .
          pnpm --filter @paraport/sdk exec biome ci .

      - name: ESLint (react)
        run: pnpm --filter @paraport/react exec eslint . --max-warnings=0

      - name: ESLint (vue)
        run: pnpm --filter @paraport/vue exec eslint . --max-warnings=0

      # Typecheck steps
      - name: Typecheck (static)
        run: pnpm --filter @paraport/static run typecheck

      - name: Typecheck (core)
        run: pnpm --filter @paraport/core run typecheck

      - name: Typecheck (vue)
        run: pnpm --filter @paraport/vue run typecheck

      - name: Typecheck (sdk)
        run: pnpm --filter @paraport/sdk run typecheck

      - name: Typecheck (react)
        run: pnpm --filter @paraport/react run typecheck

  test:
    name: Test (Node 20.x)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build @paraport/static (dependency for core tests)
        run: pnpm --filter @paraport/static build

      - name: Unit tests (@paraport/core)
        run: pnpm --filter @paraport/core test
        env:
          CI: true

  build:
    name: Build (Node 20.x)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build all packages
        run: pnpm -r --filter ./packages/* build
